### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Danielalab** [wendytamara/foodmap-power#1]
Utilizar html semántico header, section, main , nav . Mnatener una indentación de 2 espacios
tratar de evitar el código muerto si no lo utilizamos tratar de quitarlo en lugar de comentarlo
![image](https://user-images.githubusercontent.com/32286663/43652361-99d9c234-970a-11e8-9185-47c9e1a1d21c.png)
JS: Tratar de utilizar la nueva sintaxis de EC6 utilizando const y let, forEach, map, filter, reduce.
En el caso de las funciones es recomendable utilizar funciones expression (ver imagen)
ya que te obliga a declarar tus funciones antes de ejecutarlas
![image](https://user-images.githubusercontent.com/32286663/43652778-c225423a-970b-11e8-89e1-59609a3c9bc5.png)
En caso de Jquery esta bien utilizarlo, tener en cuenta que se esta dejando de usar poco a poco; así que puedes utilizar vanilla js 👍 
Ux: mostrar un mensaje al momento de identificar que este abierto un restaurante. También esta vez se dio la opción de modificar colores.
![image](https://user-images.githubusercontent.com/32286663/43652900-218e31be-970c-11e8-9dfc-922b3de39148.png)
Por último , sería bueno aprender un poco de test para poder aplicarlos y tener en cuenta separar la parte funcional de la parte presentacional (manipulación del Dom) del proyecto para tener un mayor orden.

**Comment by cureForMi** [comment]
@wendytamara  por favor, resuelve las indicaciones del issue para que los puedas cerrar así mismo te dejo el link del lms donde se ve el tema de los test, tema obligatorio de este bootcamp, por favor responde 
https://lms.laboratoria.la/cohorts/test/courses/javascript/11-testing/00-opening

**Comment by wendytamara** [comment]
@developerVilchez, he resuelto las indicaciones del issue :)
